# permissions for end users to view kubeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeconfig-viewer-role
rules:
- apiGroups:
  - kubeconfig.k8s.zoomoid.dev
  resources:
  - kubeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeconfig.k8s.zoomoid.dev
  resources:
  - kubeconfigs/status
  verbs:
  - get
